name: dienstplan
description: A app to oversee my roster

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  shared_preferences: ^2.0.15
  http: ^0.13.5
  sqflite: ^2.1.0+1
  connectivity_plus: ^2.3.9

  intl: ^0.17.0
  mobx: ^2.1.0
  flutter_mobx: ^2.0.6+4
  get_it: ^7.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

  build_runner: ^2.2.1
  mobx_codegen: ^2.0.7+3

flutter:

  uses-material-design: true
