version: '3.5'

services:
  mongodb:
    image: mongo
    volumes:
      - ./DBV:/data/db
    environment:
      MONGO_INITDB_DATABASE: dienstplanapp
      MONGO_INITDB_ROOT_USERNAME_FILE: /run/secrets/mongo_username
      MONGO_INITDB_ROOT_PASSWORD_FILE: /run/secrets/mongo_password
    secrets:
      - mongo_username
      - mongo_password
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      # start_period: 40s

  backend:
    build:
      context: .
    depends_on:
      mongodb:
        condition: service_healthy
    ports:
      - 8000:8000
    env_file:
      - ./.env
    restart: unless-stopped

secrets:
  mongo_username:
    file: ./dockerSecrets/mongo_username
  mongo_password:
    file: ./dockerSecrets/mongo_password
